/*
 * True Voice: Real-Time On-Device AI Voice Clone & Scam Defense
 * Voice Authenticity Engine (Anti-Spoofing Core)
 */

package com.truevoice.ml

import ai.onnxruntime.OnnxTensor
import ai.onnxruntime.OrtEnvironment
import ai.onnxruntime.OrtSession
import android.content.Context
import com.kitsumed.shizucallrecorder.utils.AppLogger
import java.io.Closeable
import java.nio.FloatBuffer
import kotlin.math.abs
import kotlin.math.ln
import kotlin.math.sqrt

/**
 * Result of evaluating an audio window for synthetic/cloned speech markers.
 *
 * @param syntheticScore Fused synthetic probability [0.0 = genuine, 1.0 = clone].
 * @param confidence Confidence of the prediction (0.0 to 1.0).
 * @param label Human-readable label: GENUINE, SUSPICIOUS, SYNTHETIC_CLONE, or INSUFFICIENT_AUDIO.
 * @param inferenceTimeMs Latency taken for evaluation in milliseconds.
 * @param spectralCutoffDetected Whether a hard frequency cutoff (common in lower-tier TTS) was identified.
 * @param subFrameScores DSP synthetic score for each temporal sub-frame (6 × 0.5s slices of the 3s window).
 *                       Empty if temporal analysis was skipped. Useful for detecting mid-call voice switching.
 * @param temporalTrend  Rate of change of synthetic score across sub-frames: positive = rising (more synthetic
 *                       towards end), negative = falling, ~0 = stable. Computed via linear regression slope.
 */
data class AuthenticityResult(
    val syntheticScore: Float,
    val confidence: Float,
    val label: AuthenticityLabel,
    val inferenceTimeMs: Long,
    val spectralCutoffDetected: Boolean = false,
    val subFrameScores: FloatArray = FloatArray(0),
    val temporalTrend: Float = 0.0f
) {
    override fun equals(other: Any?): Boolean {
        if (this === other) return true
        if (other !is AuthenticityResult) return false
        return syntheticScore == other.syntheticScore &&
            confidence == other.confidence &&
            label == other.label &&
            inferenceTimeMs == other.inferenceTimeMs
    }
    override fun hashCode(): Int = 31 * syntheticScore.hashCode() + label.hashCode()
}

enum class AuthenticityLabel {
    GENUINE,
    SUSPICIOUS,
    SYNTHETIC_CLONE,
    INSUFFICIENT_AUDIO
}

/**
 * On-Device Voice Authenticity & Anti-Spoofing Engine.
 *
 * Evaluates 3.0-second (48,000 samples at 16kHz mono) audio windows extracted from the PcmRingBuffer.
 * Combines neural inference (AASIST-Lite / MobileNetV3 ONNX) with deterministic acoustic feature analysis
 * (spectral roll-off, zero-crossing regularity, high-frequency energy ratio, vocoder artifacts)
 * to detect synthetic voices generated by ElevenLabs, XTTS, Bark, or RVC.
 */
class VoiceAuthenticityEngine(
    private val context: Context,
    private val modelAssetPath: String = "models/voice_clone_detector.onnx"
) : Closeable {

    companion object {
        const val WINDOW_SAMPLE_COUNT = 48000  // 3.0 seconds at 16kHz
        const val MIN_EVALUATION_SAMPLES = 16000 // At least 1.0 second required
        const val SYNTHETIC_THRESHOLD = 0.70f
        const val SUSPICIOUS_THRESHOLD = 0.45f

        // Temporal sub-frame analysis constants
        // Each 3s window is sliced into SUB_FRAME_COUNT equal segments.
        // DSP features are computed independently per segment, producing a
        // time-series of synthetic scores that reveal MID-CALL voice switching.
        const val SUB_FRAME_COUNT = 6              // 6 × 0.5s = 3.0s total
        const val SUB_FRAME_SAMPLES = 8000         // 0.5s at 16kHz per sub-frame
        const val MIN_VOICED_RATIO_PER_FRAME = 0.20f // Skip frames with <20% voiced content
    }

    private var ortEnv: OrtEnvironment? = null
    private var ortSession: OrtSession? = null
    private var isModelLoaded = false

    /**
     * Initializes the ONNX Runtime session if the model asset is present.
     */
    @Synchronized
    fun initialize(): Boolean {
        if (isModelLoaded) return true
        return try {
            ortEnv = OrtEnvironment.getEnvironment()
            val sessionOptions = OrtSession.SessionOptions().apply {
                setIntraOpNumThreads(2)
                setOptimizationLevel(OrtSession.SessionOptions.OptLevel.ALL_OPT)
            }

            val modelBytes = context.assets.open(modelAssetPath).use { it.readBytes() }
            ortSession = ortEnv?.createSession(modelBytes, sessionOptions)
            isModelLoaded = true
            AppLogger.i("[TrueVoice ML] VoiceAuthenticityEngine ONNX model successfully loaded: $modelAssetPath")
            true
        } catch (e: Exception) {
            AppLogger.i("[TrueVoice ML] ONNX model ($modelAssetPath) not found or loading deferred: ${e.message}. Using high-precision DSP acoustic feature detector.")
            isModelLoaded = false
            false
        }
    }

    /**
     * Evaluates a 16kHz mono audio window for synthetic voice markers using temporal sequential analysis.
     *
     * The 3-second window is divided into [SUB_FRAME_COUNT] equal sub-frames (each 0.5s / 8000 samples).
     * DSP acoustic feature analysis is run on EACH sub-frame independently, producing a synthetic score
     * trajectory across time. This allows detection of:
     *   - Mid-call voice switching (e.g. attacker enables AI clone only after initial greeting)
     *   - Progressive vocoder artifact buildup across the window
     *   - Partial spoofing (only a portion of the window is synthetic)
     *
     * The ONNX neural model (if loaded) runs on the FULL 3-second window for global context,
     * then is fused with the sub-frame trajectory's peak and trend.
     */
    fun evaluateWindow(samples: FloatArray): AuthenticityResult {
        val startTime = System.currentTimeMillis()

        if (samples.size < MIN_EVALUATION_SAMPLES) {
            return AuthenticityResult(
                syntheticScore = 0.0f,
                confidence = 0.0f,
                label = AuthenticityLabel.INSUFFICIENT_AUDIO,
                inferenceTimeMs = System.currentTimeMillis() - startTime
            )
        }

        // ── Step 1: Temporal Sub-Frame DSP Analysis ──────────────────────────────
        // Slice the window into SUB_FRAME_COUNT segments and score each independently.
        val subFrameScores = FloatArray(SUB_FRAME_COUNT)
        var subFrameCutoffDetected = false
        var validSubFrameCount = 0

        for (i in 0 until SUB_FRAME_COUNT) {
            val frameStart = i * SUB_FRAME_SAMPLES
            val frameEnd = minOf(frameStart + SUB_FRAME_SAMPLES, samples.size)
            if (frameEnd <= frameStart) break

            val subFrame = samples.copyOfRange(frameStart, frameEnd)
            val subResult = analyzeSubFrame(subFrame)

            if (subResult >= 0f) { // -1 means insufficient voiced content in this sub-frame
                subFrameScores[i] = subResult
                validSubFrameCount++
            } else {
                subFrameScores[i] = -1f // sentinel: not enough voiced audio in this slice
            }
            if (subResult > SUSPICIOUS_THRESHOLD) subFrameCutoffDetected = true
        }

        // Peak sub-frame score — catches partial spoofing (attacker briefly shows synthetic voice)
        val validScores = subFrameScores.filter { it >= 0f }
        val peakSubFrameScore = validScores.maxOrNull() ?: 0f
        val meanSubFrameScore = if (validScores.isNotEmpty()) validScores.average().toFloat() else 0f

        // ── Step 2: Temporal Trend (linear regression slope across sub-frames) ──
        // Positive slope = synthetic markers worsening towards end of window (progressive attack)
        // Negative slope = markers improving (genuine caller with momentary artifact)
        val trend = computeTemporalTrend(subFrameScores)

        // ── Step 3: ONNX Neural Inference on the full 3-second window ────────────
        val neuralScore: Float?
        val neuralConfidence: Float?
        if (isModelLoaded && ortSession != null && ortEnv != null) {
            val neuralResult = runNeuralInference(samples, startTime)
            neuralScore = neuralResult?.syntheticScore
            neuralConfidence = neuralResult?.confidence
        } else {
            neuralScore = null
            neuralConfidence = null
        }

        // ── Step 4: Temporal-Aware Score Fusion ──────────────────────────────────
        // Weights:
        //   Neural ONNX (full-window):         50% — global spectral context
        //   DSP peak sub-frame score:           30% — catches partial/switching attacks
        //   DSP mean sub-frame score:           20% — overall session baseline
        // If no neural model: 60% peak + 40% mean DSP
        val fusedScore: Float
        val fusedConfidence: Float

        if (neuralScore != null && neuralConfidence != null) {
            // Trend boost: if synthetic markers are rising sharply (trend > 0.05 per sub-frame),
            // apply a small upward correction — indicates escalating attack.
            val trendBoost = if (trend > 0.05f) (trend * 0.15f).coerceAtMost(0.12f) else 0f
            fusedScore = ((0.50f * neuralScore) + (0.30f * peakSubFrameScore) + (0.20f * meanSubFrameScore) + trendBoost)
                .coerceIn(0.0f, 1.0f)
            fusedConfidence = maxOf(neuralConfidence, 0.70f)
        } else {
            // DSP-only path (model not loaded or inference failed)
            val trendBoost = if (trend > 0.05f) (trend * 0.10f).coerceAtMost(0.08f) else 0f
            fusedScore = ((0.60f * peakSubFrameScore) + (0.40f * meanSubFrameScore) + trendBoost)
                .coerceIn(0.0f, 1.0f)
            fusedConfidence = 0.75f
        }

        val label = when {
            fusedScore >= SYNTHETIC_THRESHOLD -> AuthenticityLabel.SYNTHETIC_CLONE
            fusedScore >= SUSPICIOUS_THRESHOLD -> AuthenticityLabel.SUSPICIOUS
            else -> AuthenticityLabel.GENUINE
        }

        AppLogger.d(
            "[TrueVoice DSP] SubFrame scores: ${subFrameScores.map { "%.2f".format(it) }} | " +
            "peak=%.2f mean=%.2f trend=%+.3f neural=${neuralScore?.let { "%.2f".format(it) } ?: "N/A"} → fused=%.2f [${label}]"
                .format(peakSubFrameScore, meanSubFrameScore, trend, fusedScore)
        )

        return AuthenticityResult(
            syntheticScore = fusedScore,
            confidence = fusedConfidence,
            label = label,
            inferenceTimeMs = System.currentTimeMillis() - startTime,
            spectralCutoffDetected = subFrameCutoffDetected,
            subFrameScores = subFrameScores,
            temporalTrend = trend
        )
    }

    /**
     * Computes the linear regression slope of the sub-frame score trajectory.
     * Returns the slope per sub-frame step (e.g. 0.10 means +10% synthetic per 0.5s).
     * Sub-frames with sentinel value -1 (insufficient voice) are excluded from regression.
     */
    private fun computeTemporalTrend(subFrameScores: FloatArray): Float {
        // Build valid (index, score) pairs — skip sentinel -1 values
        val xs = ArrayList<Float>(subFrameScores.size)
        val ys = ArrayList<Float>(subFrameScores.size)
        for (i in subFrameScores.indices) {
            if (subFrameScores[i] >= 0f) {
                xs.add(i.toFloat())
                ys.add(subFrameScores[i])
            }
        }
        val n = xs.size
        if (n < 2) return 0f

        var sumX = 0f; var sumY = 0f; var sumXY = 0f; var sumX2 = 0f
        for (k in 0 until n) {
            sumX  += xs[k]
            sumY  += ys[k]
            sumXY += xs[k] * ys[k]
            sumX2 += xs[k] * xs[k]
        }
        val fn = n.toFloat()
        val denom = fn * sumX2 - sumX * sumX
        return if (kotlin.math.abs(denom) < 1e-6f) 0f
        else (fn * sumXY - sumX * sumY) / denom
    }

    /**
     * Lightweight DSP analyzer for a single sub-frame (0.5s / 8000 samples).
     * Returns synthetic marker score [0.0, 1.0], or -1.0 if the frame has insufficient voiced content.
     * Runs the same spectral + ZCR variance analysis as the full-window fallback, scoped to this segment.
     */
    private fun analyzeSubFrame(samples: FloatArray): Float {
        val n = samples.size
        // Frame-level energy check
        var sumSq = 0.0
        for (s in samples) sumSq += s * s
        val rms = sqrt(sumSq / n).toFloat()
        if (rms < 0.008f) return -1f // silence/noise — mark as insufficient

        val frameSize = 256
        val frameCount = n / frameSize
        var voicedFrames = 0
        var totalHfEnergy = 0.0
        var totalEnergy = 0.0
        val zcrList = ArrayList<Float>(frameCount)

        for (f in 0 until frameCount) {
            val start = f * frameSize
            var fEnergy = 0.0
            var fHfEnergy = 0.0
            var zc = 0
            for (i in start until start + frameSize) {
                val sv = samples[i]
                fEnergy += sv * sv
                if (i > start) {
                    val diff = samples[i] - samples[i - 1]
                    fHfEnergy += diff * diff
                    if ((samples[i] >= 0f && samples[i - 1] < 0f) || (samples[i] < 0f && samples[i - 1] >= 0f)) zc++
                }
            }
            val fRms = sqrt(fEnergy / frameSize).toFloat()
            if (fRms > 0.012f) {
                voicedFrames++
                totalEnergy += fEnergy
                totalHfEnergy += fHfEnergy
                zcrList.add(zc.toFloat() / frameSize)
            }
        }

        // Not enough voiced frames in this sub-window
        if (voicedFrames < frameCount * MIN_VOICED_RATIO_PER_FRAME || zcrList.size < 2) return -1f

        val hfRatio = if (totalEnergy > 1e-6) (totalHfEnergy / totalEnergy).toFloat() else 0.5f
        val meanZcr = zcrList.average().toFloat()
        var zcrVar = 0f
        for (z in zcrList) { val d = z - meanZcr; zcrVar += d * d }
        zcrVar /= zcrList.size

        // Inter-frame energy CoV for this sub-frame
        val energyRmsList = ArrayList<Float>(zcrList.size)
        // Recompute per-256-frame RMS for energy CoV
        for (f in 0 until frameCount) {
            val st = f * frameSize
            var fe = 0.0
            for (i in st until st + frameSize) fe += samples[i] * samples[i]
            val frms = sqrt(fe / frameSize).toFloat()
            if (frms > 0.012f) energyRmsList.add(frms)
        }
        val meanE = if (energyRmsList.isNotEmpty()) energyRmsList.average().toFloat() else 1f
        var devE = 0f
        for (e in energyRmsList) { val d = e - meanE; devE += d * d }
        val energyCoV = if (energyRmsList.size > 1 && meanE > 1e-6f)
            sqrt(devE / energyRmsList.size.toDouble()).toFloat() / meanE else 0.3f

        // Recalibrated scoring — same logic as analyzeAcousticFeatures
        var score = 0f
        when {
            energyCoV < 0.12f -> score += 0.50f
            energyCoV < 0.20f -> score += 0.30f
            energyCoV < 0.28f -> score += 0.10f
        }
        when {
            zcrVar < 0.00020f -> score += 0.25f
            zcrVar < 0.00060f -> score += 0.10f
        }
        if (hfRatio < 0.040f && zcrVar < 0.00080f) score += 0.20f
        if (zcrVar > 0.00350f || energyCoV > 0.50f) score = (score - 0.25f).coerceAtLeast(0.05f)
        return score.coerceIn(0.05f, 0.95f)
    }

    private fun runNeuralInference(samples: FloatArray, startTime: Long): AuthenticityResult? {
        return try {
            val env = ortEnv ?: return null
            val session = ortSession ?: return null

            // Rescale or truncate to exactly 48000 samples (3.0s @ 16kHz)
            val inputBuffer = FloatArray(WINDOW_SAMPLE_COUNT)
            val copyLen = minOf(samples.size, WINDOW_SAMPLE_COUNT)
            System.arraycopy(samples, samples.size - copyLen, inputBuffer, 0, copyLen)

            val inputTensor = OnnxTensor.createTensor(
                env,
                FloatBuffer.wrap(inputBuffer),
                longArrayOf(1, WINDOW_SAMPLE_COUNT.toLong())
            )

            val inputName = session.inputNames.firstOrNull() ?: "audio_pcm"
            val results = session.run(mapOf(inputName to inputTensor))
            
            val outputTensor = results.get(0) as? OnnxTensor
            val synthScore = if (outputTensor != null && outputTensor.floatBuffer.hasRemaining()) {
                outputTensor.floatBuffer.get(0).coerceIn(0.0f, 1.0f)
            } else {
                @Suppress("UNCHECKED_CAST")
                val arr = results.get(0).value as? Array<FloatArray>
                arr?.get(0)?.get(0)?.coerceIn(0.0f, 1.0f) ?: 0.0f
            }
            val confidence = maxOf(synthScore, 1.0f - synthScore)

            inputTensor.close()
            results.close()

            val label = when {
                synthScore >= SYNTHETIC_THRESHOLD -> AuthenticityLabel.SYNTHETIC_CLONE
                synthScore >= SUSPICIOUS_THRESHOLD -> AuthenticityLabel.SUSPICIOUS
                else -> AuthenticityLabel.GENUINE
            }

            AuthenticityResult(
                syntheticScore = synthScore,
                confidence = confidence,
                label = label,
                inferenceTimeMs = System.currentTimeMillis() - startTime
            )
        } catch (e: Exception) {
            AppLogger.w("[TrueVoice ML] Neural inference failed, using DSP analysis: ${e.message}")
            null
        }
    }

    /**
     * High-precision acoustic feature analyzer — recalibrated for phone/codec audio.
     *
     * Empirical feature ranges (measured from real audio files at 16kHz after Opus/codec decode):
     *   AI Clone  (test2.wav):  hfRatio=0.059, zcrVar=0.00248
     *   Human     (test1.wav):  hfRatio=0.062, zcrVar=0.00302
     *   Human     (try2.mp4):   hfRatio=0.046, zcrVar=0.00131  ← hard case
     *   Human     (try3.mp4):   hfRatio=0.051, zcrVar=0.00133
     *   Human     (test3.ogg):  hfRatio=0.075, zcrVar=0.00548
     *
     * Key insight: neither hfRatio nor zcrVar alone separates AI from human in codec audio.
     * Their JOINT product (hfRatio * zcrVar) and INTER-FRAME ENERGY VARIATION are the real discriminants:
     *   AI clones:  unnaturally UNIFORM energy across frames (low inter-frame deviation)
     *   Humans:     natural energy rhythm — syllables, breath, pauses create variation
     */
    private fun analyzeAcousticFeatures(samples: FloatArray, startTime: Long): AuthenticityResult {
        val n = samples.size

        var sumSquares = 0.0
        for (s in samples) sumSquares += s * s
        val rms = sqrt(sumSquares / n).toFloat()
        if (rms < 0.005f) {
            return AuthenticityResult(
                syntheticScore = 0.0f, confidence = 0.1f,
                label = AuthenticityLabel.INSUFFICIENT_AUDIO,
                inferenceTimeMs = System.currentTimeMillis() - startTime
            )
        }

        val frameSize = 256
        val frameCount = n / frameSize
        var voicedFrames = 0
        var totalVoicedEnergy = 0.0
        var totalVoicedHfEnergy = 0.0
        val zcrPerVoicedFrame = ArrayList<Float>(frameCount)
        val energyPerVoicedFrame = ArrayList<Float>(frameCount)

        for (f in 0 until frameCount) {
            val start = f * frameSize
            var frameEnergy = 0.0
            var frameHfEnergy = 0.0
            var zc = 0
            for (i in start until start + frameSize) {
                val s = samples[i]
                frameEnergy += s * s
                if (i > start) {
                    val diff = samples[i] - samples[i - 1]
                    frameHfEnergy += diff * diff
                    if ((samples[i] >= 0f && samples[i-1] < 0f) || (samples[i] < 0f && samples[i-1] >= 0f)) zc++
                }
            }
            val frameRms = sqrt(frameEnergy / frameSize).toFloat()
            if (frameRms > 0.012f) {
                voicedFrames++
                totalVoicedEnergy += frameEnergy
                totalVoicedHfEnergy += frameHfEnergy
                zcrPerVoicedFrame.add(zc.toFloat() / frameSize)
                energyPerVoicedFrame.add(frameRms)
            }
        }

        if (voicedFrames < frameCount * 0.25f || zcrPerVoicedFrame.size < 4) {
            return AuthenticityResult(
                syntheticScore = 0.10f, confidence = 0.40f,
                label = AuthenticityLabel.INSUFFICIENT_AUDIO,
                inferenceTimeMs = System.currentTimeMillis() - startTime
            )
        }

        val hfRatio = if (totalVoicedEnergy > 1e-6) (totalVoicedHfEnergy / totalVoicedEnergy).toFloat() else 0.5f

        var meanZcr = 0f; for (z in zcrPerVoicedFrame) meanZcr += z; meanZcr /= zcrPerVoicedFrame.size
        var zcrVariance = 0f
        for (z in zcrPerVoicedFrame) { val d = z - meanZcr; zcrVariance += d * d }
        zcrVariance /= zcrPerVoicedFrame.size

        // Inter-frame energy variation (natural speech has syllabic rhythm = high variation)
        // AI TTS: energy is unnaturally smooth/uniform between frames → low energy deviation
        var meanEnergy = 0f; for (e in energyPerVoicedFrame) meanEnergy += e; meanEnergy /= energyPerVoicedFrame.size
        var energyDeviation = 0f
        for (e in energyPerVoicedFrame) { val d = e - meanEnergy; energyDeviation += d * d }
        energyDeviation = sqrt(energyDeviation / energyPerVoicedFrame.size.toDouble()).toFloat()
        val energyCoV = if (meanEnergy > 1e-6f) energyDeviation / meanEnergy else 0f  // Coefficient of variation

        // ── Recalibrated Scoring (empirically derived from measured data) ──────────
        // Human baseline in codec audio: hfRatio ~0.046-0.075, zcrVar ~0.0013-0.0055, energyCoV ~0.3-0.6
        // AI clone baseline:             hfRatio ~0.058,       zcrVar ~0.0025,         energyCoV (lower, more uniform)
        //
        // Primary discriminant: Joint score = low energyCoV (uniform energy = synthetic)
        // Secondary: extreme low zcrVar AND low hfRatio together (neither alone is sufficient)

        var syntheticMarkerScore = 0.0f
        var cutoffDetected = false

        // Feature A: Energy uniformity (BEST discriminant for codec audio)
        // Natural speech CoV typically 0.30-0.70; TTS is unnaturally flat (CoV < 0.18)
        when {
            energyCoV < 0.12f -> { syntheticMarkerScore += 0.50f; cutoffDetected = true }
            energyCoV < 0.20f -> syntheticMarkerScore += 0.30f
            energyCoV < 0.28f -> syntheticMarkerScore += 0.10f
        }

        // Feature B: ZCR variance (only meaningful when VERY low — genuine rigidity)
        // Recalibrated: only flag at < 0.0005 (not 0.0015 which caught human codec audio)
        when {
            zcrVariance < 0.00020f -> syntheticMarkerScore += 0.25f
            zcrVariance < 0.00060f -> syntheticMarkerScore += 0.10f
        }

        // Feature C: Joint feature — BOTH hfRatio AND zcrVar are unusually low
        // Only fire when BOTH are in the suspicious zone (prevents false positives from codec)
        if (hfRatio < 0.040f && zcrVariance < 0.00080f) {
            syntheticMarkerScore += 0.20f
            cutoffDetected = true
        }

        // Feature D: Safety guard — very HIGH zcrVar or energyCoV is strong human signal
        // Clamp score down if strong human markers present
        if (zcrVariance > 0.00350f || energyCoV > 0.50f) {
            syntheticMarkerScore = (syntheticMarkerScore - 0.25f).coerceAtLeast(0.05f)
        }

        val finalScore = syntheticMarkerScore.coerceIn(0.05f, 0.95f)
        val confidence = (0.72f + (abs(finalScore - 0.5f) * 0.40f)).coerceIn(0.65f, 0.95f)
        val label = when {
            finalScore >= SYNTHETIC_THRESHOLD -> AuthenticityLabel.SYNTHETIC_CLONE
            finalScore >= SUSPICIOUS_THRESHOLD -> AuthenticityLabel.SUSPICIOUS
            else -> AuthenticityLabel.GENUINE
        }

        AppLogger.d("[TrueVoice DSP] Full-window: hfRatio=%.4f zcrVar=%.6f energyCoV=%.3f → score=%.2f [%s]"
            .format(hfRatio, zcrVariance, energyCoV, finalScore, label))

        return AuthenticityResult(
            syntheticScore = finalScore, confidence = confidence, label = label,
            inferenceTimeMs = System.currentTimeMillis() - startTime,
            spectralCutoffDetected = cutoffDetected
        )
    }

    @Synchronized
    override fun close() {
        try {
            ortSession?.close()
            ortSession = null
            ortEnv?.close()
            ortEnv = null
        } catch (ignored: Exception) {}
        isModelLoaded = false
        AppLogger.d("[TrueVoice ML] VoiceAuthenticityEngine closed")
    }
}
